### ISSUE TITLE
Bug: Can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [KatieBarnett/Experiments#1]
I tried to import the app-icons one. 

I get this:

![image](https://user-images.githubusercontent.com/5357526/198895051-2a41c5a6-ef8d-4553-8122-992164bedb0d.png)

```
A problem occurred configuring project ':graphql'.
> Could not resolve all files for configuration ':graphql:classpath'.
   > Could not resolve com.apollographql.apollo3:apollo-gradle-plugin:3.5.0.
     Required by:
         project :graphql > com.apollographql.apollo3:com.apollographql.apollo3.gradle.plugin:3.5.0
      > Could not resolve com.apollographql.apollo3:apollo-gradle-plugin:3.5.0.
         > Could not get resource 'https://plugins.gradle.org/m2/com/apollographql/apollo3/apollo-gradle-plugin/3.5.0/apollo-gradle-plugin-3.5.0.module'.
            > Could not GET 'https://jcenter.bintray.com/com/apollographql/apollo3/apollo-gradle-plugin/3.5.0/apollo-gradle-plugin-3.5.0.module'.
               > Read timed out

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

Android Studio Flamingo | 2022.2.1 Canary 6
Build #AI-222.4345.14.2221.9189903, built on October 18, 2022
Runtime version: 17.0.4.1+0-b2043.56-9127311 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4000M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    debugger.watches.in.variables=false
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.vecheslav.darculaDarkerTheme (1.2.0)
    com.intellij.marketplace (222.4345.24)
    com.dubreuia (2.3.0)
    com.github.beansoft.jadx.gui.idea (2022.1.0)
    net.aquadc.mike.plugin (0.26)
    com.google.mad-scorecard (1.2)
    Show As ... (1.0.3)

**Comment by KatieBarnett** [comment]
Hi, they are all part of the same project, they are not separate apps. I do have a core module that includes the theming and other common items for all of my experiments. 
If you import from the top level it should work.

**Comment by AndroidDeveloperLB** [comment]
@KatieBarnett Oh ok. I saw some article on Medium that links to the app-icons part, so I thought it's a stand alone.

**Comment by AndroidDeveloperLB** [comment]
@KatieBarnett Still it failed to open the main one. Look:

![image](https://user-images.githubusercontent.com/5357526/199366038-19fa8d19-b66c-4099-845e-ff42e3aaa323.png)
